
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.18.7-76061807-generic - x86_64
...
