load("@rules_swift//swift:swift.bzl", "swift_library")

package(default_visibility = ["//visibility:public"])

swift_library(
    name = "Robot",
    srcs = ["RobotDefinition.swift"],
    module_name = "Robot",
)
